import { TypographyOptions } from '@mui/material/styles/createTypography'

//this setup must be aling to style guide of client
export const typography: TypographyOptions = {
    fontFamily: 'Roboto, sans-serif',
    htmlFontSize: 16,
    fontWeightLight: 400,
    fontWeightRegular: 600,
    fontWeightMedium: 700,
    fontWeightBold: 900,
    h1: {
        fontFamily: 'Roboto, sans-serif',
        fontWeight: 900,
        fontSize: '2.5rem',
        lineHeight: 1.2,
        letterSpacing: '0.5px',
        paddingBottom: '0.5rem',
        marginTop: '0',
        color: '#18243E',
    },
    h2: {
        fontFamily: 'Roboto, sans-serif',
        fontWeight: 600,
        fontSize: '2rem',
        lineHeight: 1.2,
        letterSpacing: '0.5px',
        paddingBottom: '0.5rem',
        marginTop: '0',
        color: '#18243E',
    },
    h3: {
        fontFamily: 'Roboto, sans-serif',
        fontWeight: 600,
        fontSize: '1.5rem',
        lineHeight: 1.2,
        letterSpacing: '0.5px',
        paddingBottom: '0.5rem',
        marginTop: '0',
        color: '#18243E',
    },
    h4: {
        fontFamily: 'Roboto, sans-serif',
        fontWeight: 700,
        fontSize: '1rem',
        lineHeight: 1.2,
        letterSpacing: '0.5px',
        paddingBottom: '0.5rem',
        marginTop: '0',
        color: '#18243E',
    },
    h5: {
        fontFamily: 'Roboto, sans-serif',
        fontWeight: 700,
        fontSize: '0.875rem',
        lineHeight: 1.2,
        letterSpacing: '0.5px',
        paddingBottom: '0.5rem',
        marginTop: '0',
        color: '#18243E',
    },
    h6: {
        fontFamily: 'Roboto, sans-serif',
        fontWeight: 700,
        fontSize: '0.75rem',
        lineHeight: 1.2,
        letterSpacing: '0.5px',
        paddingBottom: '0.5rem',
        marginTop: '0',
        color: '#18243E',
    },
    body1: {
        fontFamily: 'Roboto, sans-serif',
        fontWeight: 400,
        fontSize: '1rem',
        lineHeight: 1.2,
        letterSpacing: '0.5px',
        paddingBottom: '0.5rem',
        marginTop: '0',
        color: '#18243E',
    },
    body2: {
        fontFamily: 'Roboto, sans-serif',
        fontWeight: 400,
        fontSize: '75%',
        lineHeight: 1.2,
        letterSpacing: '0.5px',
        paddingBottom: '0.5rem',
        marginTop: '0',
        color: '#18243E',
    },
    button: {
        fontFamily: 'Roboto, sans-serif',
    },
}
